### ISSUE TITLE
Is Imagenet rec file available?

### ISSUE THREAD

**Issue by miguelgfierro** [tornadomeet/ResNet#16]
I´m wondering if the Imagenet  rec file you used to train the network is available, or at least the data you used with im2rec to generate the rec file

**Comment by tornadomeet** [comment]
the data is the original imagenet data, http://image-net.org/download

**Comment by tornadomeet** [comment]
the rec file is too big, so you should convert the rec file by yourself~

**Comment by miguelgfierro** [comment]
thanks
