### ISSUE TITLE
Imagenet11K synset

### ISSUE THREAD

**Issue by Darwin2011** [tornadomeet/ResNet#23]
@tornadomeet 

Could you please show me how I can get the syntex for imagenet 11k? 
Thanks a lot.

**Comment by tornadomeet** [comment]
cc @mli

**Comment by tornadomeet** [comment]
@Darwin2011  here: http://data.mxnet.io/models/imagenet-11k/synset.txt  
the usage is here: https://github.com/dmlc/mxnet-notebooks/blob/master/python/tutorials/predict_imagenet.ipynb

**Comment by Darwin2011** [comment]
@tornadomeet Thanks.
