### ISSUE TITLE
rgb channel in predict.py

### ISSUE THREAD

**Issue by mli** [tornadomeet/ResNet#25]
you need to use `cv2.cvtColor(cv2.imread(filename), cv2.COLOR_BGR2RGB)` to switch to rgb. see example https://github.com/dmlc/mxnet-notebooks/blob/master/python/tutorials/predict_imagenet.ipynb

**Comment by tornadomeet** [comment]
oh, sorry. update by https://github.com/tornadomeet/ResNet/pull/26
