### ISSUE TITLE
Why are RELU and BN set before Conv?

### ISSUE THREAD

**Issue by cuteding** [tornadomeet/ResNet#39]
https://github.com/tornadomeet/ResNet/blob/master/symbol_resnet.py
In line 28:

        bn1 = mx.sym.BatchNorm(data=data, fix_gamma=False, eps=2e-5, momentum=bn_mom, name=name + '_bn1')
        act1 = mx.sym.Activation(data=bn1, act_type='relu', name=name + '_relu1')
        conv1 = mx.sym.Convolution(data=act1, num_filter=int(num_filter*0.25), kernel=(1,1), stride=(1,1), pad=(0,0),

bn1 and act1 layer is set before conv1, why?

**Comment by tornadomeet** [comment]
please read the original paper.  Identity Mappings in Deep Residual Networks

**Comment by cuteding** [comment]
THX
