### ISSUE TITLE
Why no_bias=True in Conv layers?

### ISSUE THREAD

**Issue by jonbakerfish** [tornadomeet/ResNet#7]
Why there is [`no_bias=True`](https://github.com/tornadomeet/ResNet/blob/master/symbol_resnet.py) for conv layer?

**Comment by tornadomeet** [comment]
because there is BN after every conv, and BN has `bias`, it should have the same effect, another, `no_bias=True` will decrease the calc.

**Comment by jonbakerfish** [comment]
@tornadomeet OK, thanks.
